#!/bin/sh -e

## Copyright (c) 2011, Georgia Tech Research Corporation
## All rights reserved.
##
## Author(s): Neil T. Dantam   <ntd@gatech.edu>
## Georgia Tech Humanoid Robotics Lab
## Under Direction of Prof. Mike Stilman <mstilman@cc.gatech.edu>
##
##
## This file is provided under the following "BSD-style" License:
##
##
##   Redistribution and use in source and binary forms, with or
##   without modification, are permitted provided that the following
##   conditions are met:
##
##   * Redistributions of source code must retain the above copyright
##     notice, this list of conditions and the following disclaimer.
##
##   * Redistributions in binary form must reproduce the above
##     copyright notice, this list of conditions and the following
##     disclaimer in the documentation and/or other materials provided
##     with the distribution.
##
##   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
##   CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
##   INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
##   MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
##   DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
##   CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
##   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
##   LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
##   USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
##   AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
##   LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
##   ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
##   POSSIBILITY OF SUCH DAMAGE.


test_true() {
    echo -n Testing true:  $@ "\t"
    if $@ 2> /dev/null; then
        echo OK
    else
        echo FAILED
        exit 1
    fi
}

test_false() {
    echo -n Testing false:  $@ "\t"
    if $@ 2> /dev/null; then
        echo FAILED
        exit 1
    else
        echo OK
    fi
}

test_true true
test_false false

test_true ./achcop true
test_false ./achcop false
test_true ./achcop sleep 5

test_true ./achcop -r true
test_false ./achcop -r false
test_true ./achcop -r sleep 5

test_true ./achcop -d true
test_false ./achcop -d false
test_true ./achcop -d sleep 5

test_true ./achcop -dr true
test_false ./achcop -dr false
test_true ./achcop -dr sleep 5
